name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: demo
        type: choice
        options:
          - demo
          - qa
          - trunk

      project:
        description: "Select project"
        required: true
        default: chromium
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - api
          - all

      tags:
        description: "Run by tag (optional, e.g. @smoke or @api)"
        required: false
        default: ""

  push:
    branches: [main, master]

  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install deps
      - name: Install dependencies
        run: npm ci

      # Install browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      #  Run tests dynamically
      - name: Run Playwright Tests
        run: |
          CMD="npx playwright test"

          PROJECT="${{ github.event.inputs.project }}"
          TAGS="${{ github.event.inputs.tags }}"

          echo "Selected Project: $PROJECT"
          echo "Selected Tags: $TAGS"

          # Apply project
          if [ "$PROJECT" != "all" ]; then
            CMD="$CMD --project=$PROJECT"
          fi

          # Validate invalid combinations
          if [[ "$PROJECT" == "chromium" || "$PROJECT" == "firefox" || "$PROJECT" == "webkit" ]]; then
            if [[ "$TAGS" == *"@api"* ]]; then
              echo "❌ ERROR: Cannot run @api tests on UI project ($PROJECT)"
              exit 1
            fi
          fi

          if [[ "$PROJECT" == "api" ]]; then
            if [[ "$TAGS" == *"@ui"* ]]; then
              echo "❌ ERROR: Cannot run @ui tests on API project"
              exit 1
            fi
          fi

          # Apply tag filter
          if [ -n "$TAGS" ]; then
            CMD="$CMD --grep='$TAGS'"
          fi

          echo "🚀 Running Command: $CMD"
          eval $CMD

        env:
          ENV_NAME: ${{ github.event.inputs.env || 'demo' }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      # Upload Playwright HTML report
      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Upload Allure raw results
      - name: Upload Allure Results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 30
